import{a as v,S as z,i as E}from"./assets/vendor-BJVfH36N.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))i(r);new MutationObserver(r=>{for(const n of r)if(n.type==="childList")for(const f of n.addedNodes)f.tagName==="LINK"&&f.rel==="modulepreload"&&i(f)}).observe(document,{childList:!0,subtree:!0});function t(r){const n={};return r.integrity&&(n.integrity=r.integrity),r.referrerPolicy&&(n.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?n.credentials="include":r.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function i(r){if(r.ep)return;r.ep=!0;const n=t(r);fetch(r.href,n)}})();const I="53213667-a2fc459fbd1b81236d446f31b",P="https://pixabay.com/api/",S=40;async function p(e,o=1){try{const t=await v.get(P,{params:{key:I,q:e,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:S,page:o}});return{hits:t.data.hits,totalHits:t.data.totalHits}}catch(t){throw console.error("API isteği sırasında bir hata oluştu:",t.message),new Error("API isteği başarısız oldu.")}}const A=document.querySelector(".search-form"),s=document.querySelector(".gallery-list"),d=document.querySelector("#loader"),m=document.querySelector(".load-more-btn");let c=1,h="",l=0;const H=new z(".gallery a");u();function M(){d.classList.remove("hidden")}function T(){d.classList.add("hidden")}A.addEventListener("submit",x);m.addEventListener("click",B);async function x(e){e.preventDefault();const o=e.target.elements.searchQuery.value.trim();if(!o){a("info","Arama alanı boş olamaz!");return}h=o,c=1,s.innerHTML="",u(),L();try{const{hits:t,totalHits:i}=await p(h,c);if(l=i,t.length===0){a("error","Üzgünüz, arama sorgunuza uygun görsel bulunamadı. Lütfen tekrar deneyin!");return}g(t),l>t.length&&w(),y()}catch(t){a("error","Bir hata oluştu. Lütfen daha sonra tekrar deneyin."),console.error(t)}finally{b()}}async function B(){c+=1,L(),M(),u();try{const{hits:e}=await p(h,c);g(e,!1),$(),y()}catch(e){a("error","Görseller yüklenirken bir hata oluştu."),console.error(e)}finally{b(),T()}}function g(e,o=!0){const t=e.map(O).join("");o?s.innerHTML=t:s.insertAdjacentHTML("beforeend",t),H.refresh()}function O(e){return`
    <li class="image-card">
      <a href="${e.largeImageURL}">
        <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
        <div class="info">
          <p><b>Likes</b> ${e.likes}</p>
          <p><b>Views</b> ${e.views}</p>
          <p><b>Comments</b> ${e.comments}</p>
          <p><b>Downloads</b> ${e.downloads}</p>
        </div>
      </a>
    </li>
  `}function y(){s.children.length>=l?(u(),l>0&&a("info","Üzgünüz, arama sonuçlarının sonuna ulaştınız.")):w()}function $(){const e=s.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}function L(){d.classList.remove("hidden")}function b(){d.classList.add("hidden")}function w(){m.classList.remove("hidden")}function u(){m.classList.add("hidden")}function a(e,o){E[e]({message:o,position:"topRight",timeout:3e3})}
//# sourceMappingURL=index.js.map
